# name: Build and Deploy NextJS App to Server

# on:
#   push:
#     branches: [dev]
#   pull_request:
#     branches: [dev]

# # Tránh deploy chồng chéo
# concurrency:
#   group: fe-deploy
#   cancel-in-progress: true

# env:
#   DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/jobhuntly-frontend
#   DOCKER_TAG: latest
#   REMOTE_DIR: ~/jobhuntly-fe

# jobs:
#   build:
#     name: Build NextJS App
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22.2.0"

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Setup Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Docker Image
#         if: github.event_name == 'push'
#         run: |
#           docker build \
#             --no-cache \
#             --build-arg NEXT_PUBLIC_API_PROXY_TARGET="${{ secrets.NEXT_PUBLIC_API_PROXY_TARGET }}" \
#             --build-arg NEXT_PUBLIC_API_BASE_URL="${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" \
#             --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" \
#             --build-arg NEXT_PUBLIC_WS_ENDPOINT="${{secrets.NEXT_PUBLIC_WS_ENDPOINT}}" \
#             --build-arg NEXT_PUBLIC_SUB_DEST="${{secrets.NEXT_PUBLIC_SUB_DEST}}" \
#             -t $DOCKER_IMAGE:$DOCKER_TAG .
#           docker push $DOCKER_IMAGE:$DOCKER_TAG

#       - name: Create environment file
#         if: github.event_name == 'push'
#         run: |
#           {
#             echo "NEXT_PUBLIC_API_PROXY_TARGET=${{ secrets.NEXT_PUBLIC_API_PROXY_TARGET }}";
#             echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}";
#             echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}";
#             echo "NEXT_PUBLIC_WS_ENDPOINT=${{secrets.NEXT_PUBLIC_WS_ENDPOINT}}";
#             echo "NEXT_PUBLIC_SUB_DEST=${{secrets.NEXT_PUBLIC_SUB_DEST}}";
#           } > .env.production
      
      

#       - name: Copy Next.js files to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           source: "docker-compose.yml,.env.production"
#           target: "${{ env.REMOTE_DIR }}"
#           overwrite: true

#   deploy:
#     name: Deploy NextJS App
#     runs-on: ubuntu-latest
#     needs: [build]
#     if: github.event_name == 'push'
#     steps:
#       - name: Deploying
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             if docker compose version >/dev/null 2>&1; then
#             COMPOSE="docker compose"
#             else
#             COMPOSE="docker-compose"
#             fi
#             echo "Using: $COMPOSE"
            
#             echo "Navigating to project directory..."
#             cd ${{ env.REMOTE_DIR }}
            
#             echo "Setting up environment variables..."
#             # Tạo .env file với API URL từ secrets
#             cp .env.production .env

#             echo "Creating network (if not exists)..."
#             echo "Currently, we re-use jobhuntly-network..."
#             docker network create jobhuntly-network || true

#             echo "Pulling latest image..."
#             $COMPOSE -f docker-compose.yml pull

#             echo "Stopping old container if exists..."
#             $COMPOSE -f docker-compose.yml stop jobhuntly_fe || true
#             $COMPOSE -f docker-compose.yml rm -f jobhuntly_fe || true
#             docker rm -f jobhuntly_fe || true 

#             echo "Starting new container with correct name..."
#             $COMPOSE -f docker-compose.yml up -d --remove-orphans
            
#             echo "Show status..."
#             $COMPOSE -f docker-compose.yml ps

#             echo "Deployment completed!"
